import localFont from 'next/font/local';
import '@/app/ui/styles/reset.css';
import '@/app/ui/styles/globals.scss';

const geistSans = localFont({
    src: './ui/fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './ui/fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata = {
    title: 'Cinepop',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
            <body className={`${geistSans.className} ${geistMono.className}`}>{children}</body>
        </html>
    );
}
