import localFont from 'next/font/local';
import '@/app/ui/styles/reset.css';

const instrumentSans = localFont({
    src: './ui/fonts/InstrumentSans-Variable.ttf',
    variable: '--font-instrument-sans',
    weight: '100 900',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: {
        icon: './favicon.ico',
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
            <body className={`${instrumentSans.className}`}>{children}</body>
        </html>
    );
}
